create user empresa identified by "Riodejaneiro123" account unlock default tablespace data;
GRANT CREATE SESSION TO empresa;
ALTER USER empresa quota unlimited on data;

CREATE TABLE empresa.employees (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    salary number NOT NULL
);
